name: Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-and-push:
      runs-on: ubuntu-18.04
      # if: github.ref == 'refs/heads/master'
      steps:
        - name: Create variables
          run: |
            echo "CURRENT_DATE_TIME=$(date --utc +%Y%m%d.%H%M)" >> $GITHUB_ENV
            echo "SHORT_SHA=$(GITHUB_SHA:0:8)" >> $GITHUB_ENV
            echo "SHORT_SHA=${GITHUB_REF/refs\/heads\//} >> $GITHUB_ENV
        - uses: actions/checkout@v2
          with:
            submodules: true
      #   -
      #     name: Login to DockerHub
      #     uses: docker/login-action@v1 
      #     with:
      #       username: ${{ secrets.DOCKERHUB_USERNAME }}
      #       password: ${{ secrets.DOCKERHUB_TOKEN }}
      #   -
      #     name: Build and push
      #     id: docker_build
      #     uses: docker/build-push-action@v2
      #     with:
      #       push: true
      #       tags: $GITHUB_REPOSITORY:latest, $GITHUB_REPOSITORY:
      # -
      #   name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}


