name: Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-and-push:
      runs-on: ubuntu-18.04
      # if: github.ref == 'refs/heads/master'
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: true
        -
          run: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
            docker build --no-cache -t $GITHUB_REPOSITORY:latest -t $GITHUB_REPOSITORY:${GITHUB_REF/refs\/heads\//}-${GITHUB_SHA:0:8}-${date --utc +%Y%m%d.%H%M} .
            docker push --all-tags $GITHUB_REPOSITORY
          env:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}


