name: Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
    tags:
      - '*'

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
      runs-on: ubuntu-18.04
      if: github.ref == 'refs/heads/master'
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: true
        - name: build & push
          run: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker build --no-cache -t $DOCKER_USERNAME/$REPO_NAME:latest .
            docker push $DOCKER_USERNAME/$REPO_NAME:latest
            .scripts/github/retag-and-push.sh $REPO_NAME latest
          env:
            REPO_NAME: ${{ github.event.repository.name }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


